apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-config
  namespace: helpdesk
data:
  # Django Settings
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,your-domain.com"
  CORS_ALLOWED_ORIGINS: "https://your-domain.com,https://app.your-domain.com"
  
  # DigitalOcean Database Configuration
  DB_HOST: "helpdesk-production-postgres-do-user-12345678-0.db.ondigitalocean.com"
  DB_NAME: "helpdesk"
  DB_USER: "helpdesk_user"
  DB_PORT: "25060"
  DB_SSLMODE: "require"
  
  # Redis Configuration (using in-memory for DO)
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  
  # Email Configuration (using external SMTP)
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"
  DEFAULT_FROM_EMAIL: "helpdesk@your-domain.com"
  
  # DigitalOcean Spaces Configuration
  AWS_ACCESS_KEY_ID: ""  # Will be set from secrets
  AWS_SECRET_ACCESS_KEY: ""  # Will be set from secrets
  AWS_STORAGE_BUCKET_NAME: "helpdesk-production-static"
  AWS_S3_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
  AWS_S3_CUSTOM_DOMAIN: "helpdesk-production-static.nyc3.digitaloceanspaces.com"
  
  # Security Settings
  SECURE_BROWSER_XSS_FILTER: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  X_FRAME_OPTIONS: "DENY"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  
  # File Upload Settings
  FILE_UPLOAD_MAX_MEMORY_SIZE: "10485760"  # 10MB
  DATA_UPLOAD_MAX_MEMORY_SIZE: "10485760"  # 10MB
  FILE_UPLOAD_MAX_SIZE: "10485760"  # 10MB
  
  # Cache Settings
  CACHE_TTL: "300"
  
  # Business Hours
  BUSINESS_HOURS_START: "9"
  BUSINESS_HOURS_END: "17"
  BUSINESS_TIMEZONE: "UTC"
  
  # Backup Settings
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_COMPRESSION: "True"
  
  # Security Monitoring Thresholds
  SECURITY_FAILED_LOGIN_THRESHOLD: "5"
  SECURITY_SUSPICIOUS_ACTIVITY_THRESHOLD: "10"
  SECURITY_DATA_BREACH_THRESHOLD: "1"
  SECURITY_PRIVILEGE_ESCALATION_THRESHOLD: "1"
  SECURITY_UNUSUAL_ACCESS_THRESHOLD: "3"
  
  # DigitalOcean Monitoring
  DO_MONITORING_ENABLED: "True"
  DO_ALERT_EMAIL: "admin@your-domain.com"
