apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: helpdesk
  labels:
    app: ai-service
    component: ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
        component: ai
    spec:
      containers:
      - name: ai-service
        image: your-registry/helpdesk-ai:latest
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: REDIS_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: ANTHROPIC_API_KEY
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: helpdesk
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP

