apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: helpdesk
  labels:
    app: celery-worker
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
        component: worker
    spec:
      containers:
      - name: celery-worker
        image: your-registry/helpdesk-django:latest
        command: ["celery", "-A", "config", "worker", "-l", "info", "--concurrency=4", "--max-tasks-per-child=1000"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DJANGO_SETTINGS_MODULE
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DEBUG
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_USER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: CELERY_RESULT_BACKEND
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: EMAIL_PORT
        - name: EMAIL_USE_TLS
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: EMAIL_USE_TLS
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DEFAULT_FROM_EMAIL
        # Secret values
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: DB_PASSWORD
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: EMAIL_HOST_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: AWS_STORAGE_BUCKET_NAME
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: media-files
          mountPath: /app/media
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: media-files
        emptyDir: {}
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: helpdesk
  labels:
    app: celery-beat
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
        component: scheduler
    spec:
      containers:
      - name: celery-beat
        image: your-registry/helpdesk-django:latest
        command: ["celery", "-A", "config", "beat", "-l", "info"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DJANGO_SETTINGS_MODULE
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DEBUG
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_USER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: DB_PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: helpdesk-config
              key: CELERY_RESULT_BACKEND
        # Secret values
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpdesk-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always

