apiVersion: v1
kind: ConfigMap
metadata:
  name: helpdesk-config
  namespace: helpdesk
data:
  # Django Settings
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,your-domain.com"
  CORS_ALLOWED_ORIGINS: "https://your-domain.com,https://app.your-domain.com"
  
  # Database Configuration
  DB_HOST: "your-rds-endpoint.amazonaws.com"
  DB_NAME: "helpdesk"
  DB_USER: "helpdesk_user"
  DB_PORT: "5432"
  
  # Redis Configuration
  REDIS_URL: "redis://your-redis-endpoint.cache.amazonaws.com:6379/0"
  CELERY_BROKER_URL: "redis://your-redis-endpoint.cache.amazonaws.com:6379/0"
  CELERY_RESULT_BACKEND: "redis://your-redis-endpoint.cache.amazonaws.com:6379/0"
  
  # Email Configuration
  EMAIL_HOST: "smtp.amazonaws.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  DEFAULT_FROM_EMAIL: "noreply@your-domain.com"
  
  # Security Settings
  SECURE_BROWSER_XSS_FILTER: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  X_FRAME_OPTIONS: "DENY"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  
  # File Upload Settings
  FILE_UPLOAD_MAX_MEMORY_SIZE: "10485760"  # 10MB
  DATA_UPLOAD_MAX_MEMORY_SIZE: "10485760"  # 10MB
  FILE_UPLOAD_MAX_SIZE: "10485760"  # 10MB
  
  # Cache Settings
  CACHE_TTL: "300"
  
  # Business Hours
  BUSINESS_HOURS_START: "9"
  BUSINESS_HOURS_END: "17"
  BUSINESS_TIMEZONE: "UTC"
  
  # Backup Settings
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_COMPRESSION: "True"
  
  # Security Monitoring Thresholds
  SECURITY_FAILED_LOGIN_THRESHOLD: "5"
  SECURITY_SUSPICIOUS_ACTIVITY_THRESHOLD: "10"
  SECURITY_DATA_BREACH_THRESHOLD: "1"
  SECURITY_PRIVILEGE_ESCALATION_THRESHOLD: "1"
  SECURITY_UNUSUAL_ACCESS_THRESHOLD: "3"

