name: helpdesk-platform

services:
  - name: django-backend
    github:
      repo: Ashour158/Desk
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    build_command: pip install -r requirements.txt
    # The key fix: Add PYTHONPATH and cd to core directory before running gunicorn
    run_command: cd core && PYTHONPATH=/workspace/core gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 2 --timeout 120 --access-logfile - --error-logfile - --log-level info
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: helpdesk
  
  - name: redis
    engine: REDIS
    production: true
    cluster_name: helpdeskv

envs:
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: GGQVu%4FV6BdKUe2ct4i(c-J!iJxoI8RXC=%ayE-z85tbq6yLc
  
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  
  - key: ALLOWED_HOSTS
    scope: RUN_TIME
    value: ".ondigitalocean.app"
  
  - key: DISABLE_COLLECTSTATIC
    scope: BUILD_TIME
    value: "1"
  
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: config.settings.production
  
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  
  - key: DB_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  
  - key: DB_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  
  - key: DB_NAME
    scope: RUN_TIME
    value: ${db.DATABASE}
  
  - key: DB_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: ${db.PASSWORD}
  
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  - key: CELERY_BROKER_URL
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  - key: CELERY_RESULT_BACKEND
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  - key: SECURE_SSL_REDIRECT
    scope: RUN_TIME
    value: "False"
  
  - key: SESSION_COOKIE_SECURE
    scope: RUN_TIME
    value: "False"
  
  - key: CSRF_COOKIE_SECURE
    scope: RUN_TIME
    value: "False"

region: fra
