name: helpdesk-platform

# ===================================
# MAIN SERVICE - Django Backend
# ===================================

services:
  - name: django-backend
    github:
      repo: Ashour158/Desk
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 2 --chdir core
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      # Django Settings
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: config.settings.production
      
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: /workspace/core

# ===================================
# DATABASES
# ===================================

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: helpdesk
  
  - name: redis
    engine: REDIS
    production: true
    cluster_name: helpdeskv

# ===================================
# ENVIRONMENT VARIABLES
# ===================================

envs:
  # Django Settings
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: GGQVu%4FV6BdKUe2ct4i(c-J!iJxoI8RXC=%ayE-z85tbq6yLc
  
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  
  - key: ALLOWED_HOSTS
    scope: RUN_TIME
    value: ".ondigitalocean.app"
  
  - key: DISABLE_COLLECTSTATIC
    scope: BUILD_TIME
    value: "1"
  
  # Database Connection
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  
  - key: DB_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  
  - key: DB_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  
  - key: DB_NAME
    scope: RUN_TIME
    value: ${db.DATABASE}
  
  - key: DB_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: ${db.PASSWORD}
  
  # Redis Connection
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  - key: CELERY_BROKER_URL
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  - key: CELERY_RESULT_BACKEND
    scope: RUN_TIME
    value: ${redis.DATABASE_URL}
  
  # Security
  - key: SECURE_SSL_REDIRECT
    scope: RUN_TIME
    value: "True"
  
  - key: SESSION_COOKIE_SECURE
    scope: RUN_TIME
    value: "True"
  
  - key: CSRF_COOKIE_SECURE
    scope: RUN_TIME
    value: "True"

# ===================================
# REGION
# ===================================

region: fra
