# AlertManager Configuration for Helpdesk Platform

global:
  smtp_smarthost: 'smtp.amazonaws.com:587'
  smtp_from: 'alerts@your-domain.com'
  smtp_auth_username: 'your-smtp-username'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@your-domain.com'
    subject: '[CRITICAL] Helpdesk Platform Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Severity: {{ .GroupLabels.severity }}
      Service: {{ .GroupLabels.service }}
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts'
    title: 'Critical Alert: Helpdesk Platform'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

- name: 'warning-alerts'
  email_configs:
  - to: 'devops@your-domain.com'
    subject: '[WARNING] Helpdesk Platform Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Severity: {{ .GroupLabels.severity }}
      Service: {{ .GroupLabels.service }}
      Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

# Alert Rules
groups:
- name: helpdesk.rules
  rules:
  - alert: DjangoAppDown
    expr: up{job="django-app"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Django application is down"
      description: "Django application has been down for more than 1 minute"

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 10% for more than 2 minutes"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time"
      description: "95th percentile response time is above 2 seconds"

  - alert: DatabaseConnectionsHigh
    expr: django_db_connections_active > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High database connections"
      description: "Database connections are above 80"

  - alert: CacheHitRateLow
    expr: rate(django_cache_hits_total[5m]) / rate(django_cache_requests_total[5m]) < 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low cache hit rate"
      description: "Cache hit rate is below 80%"

  - alert: CeleryTasksFailed
    expr: rate(celery_tasks_failed_total[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High Celery task failure rate"
      description: "Celery task failure rate is above 10%"

  - alert: MemoryUsageHigh
    expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 80%"

  - alert: CPUUsageHigh
    expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is above 80%"

  - alert: DiskSpaceLow
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Low disk space"
      description: "Disk space is below 10%"

  - alert: RedisDown
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Redis is down"
      description: "Redis cache is not responding"

  - alert: DatabaseDown
    expr: up{job="postgres"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Database is down"
      description: "PostgreSQL database is not responding"

