[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "config.settings.production"
PYTHONPATH = "/app"
DJANGO_DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app,*.up.railway.app"

# Database
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
DB_ENGINE = "django.db.backends.postgresql"
DB_NAME = "${{Postgres.POSTGRES_DB}}"
DB_USER = "${{Postgres.POSTGRES_USER}}"
DB_PASSWORD = "${{Postgres.POSTGRES_PASSWORD}}"
DB_HOST = "${{Postgres.POSTGRES_HOST}}"
DB_PORT = "${{Postgres.POSTGRES_PORT}}"

# Redis
REDIS_URL = "${{Redis.REDIS_URL}}"
CELERY_BROKER_URL = "${{Redis.REDIS_URL}}"
CELERY_RESULT_BACKEND = "${{Redis.REDIS_URL}}"

# Security
SECRET_KEY = "${{SECRET_KEY}}"
DJANGO_SECRET_KEY = "${{SECRET_KEY}}"

# File Storage (Railway Volumes)
MEDIA_ROOT = "/app/media"
STATIC_ROOT = "/app/staticfiles"

# Email (SendGrid)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = "True"
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = "${{SENDGRID_API_KEY}}"

# Monitoring
SENTRY_DSN = "${{SENTRY_DSN}}"

# CORS
CORS_ALLOWED_ORIGINS = "https://helpdesk.railway.app,https://helpdesk.up.railway.app"
CORS_ALLOW_CREDENTIALS = "True"
